version: '3'
services:
  db:
    image: 'mysql:5.7'
    restart: always
    volumes:
      - D:\data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - "3307:3307"
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_unicode_ci
